import Foundation
import ArgumentParser
import Picaroon
import Flynn
import Hitch
import Spanker

public typealias DocumentUUID = Hitch
public typealias DocumentContent = Hitch
public typealias DocumentVersion = Int

public typealias UserUUID = Hitch
public typealias Error = HalfHitch

public class Endeavour: Actor {
    public static let shared = Endeavour()
    override private init() {}

    private var documents: [DocumentUUID: Document] = [:]

    private func _beNewDocument(userUUID: UserUUID,
                                content: Hitch?,
                                _ returnCallback: @escaping (DocumentInfo?, Document?, Error?) -> Void) {
        let document = Document(owner: userUUID,
                                content: content)
        document.beGetInfo(user: userUUID, self) { documentInfo, error in
            guard error == nil else { return returnCallback(nil, nil, error) }
            guard let documentInfo = documentInfo else { return returnCallback(nil, nil, "document info is missing") }
            self.documents[documentInfo.uuid] = document
            returnCallback(documentInfo, document, nil)
        }
    }

    private func _beNewDocument(userUUID: UserUUID,
                                named: Hitch?,
                                content: Hitch?,
                                _ returnCallback: @escaping (DocumentInfo?, Document?, Error?) -> Void) {
        let document = Document(owner: userUUID,
                                named: named,
                                content: content)
        document.beGetInfo(user: userUUID, self) { documentInfo, error in
            guard error == nil else { return returnCallback(nil, nil, error) }
            guard let documentInfo = documentInfo else { return returnCallback(nil, nil, "document info is missing") }
            self.documents[documentInfo.uuid] = document
            returnCallback(documentInfo, document, nil)
        }
    }

    private func _beJoinDocument(userUUID: UserUUID,
                                 documentUUID: DocumentUUID,
                                 _ returnCallback: @escaping (DocumentInfo?, Document?, Error?) -> Void) {
        guard let document = documents[documentUUID] else {
            return returnCallback(nil, nil, "The document does not exist")
        }
        document.beAdd(user: userUUID,
                       self,
                       returnCallback)
    }

    private func _beLeaveDocument(userUUID: UserUUID,
                                  service: Service,
                                  documentUUID: DocumentUUID,
                                  _ returnCallback: @escaping (Error?) -> Void) {
        guard let document = documents[documentUUID] else {
            return returnCallback("The document does not exist")
        }

        document.beLeave(user: userUUID,
                         service: service,
                         self) { closed, error in
            if closed {
                self.documents[documentUUID] = nil
            }
            returnCallback(error)
        }
    }
}

// MARK: - Autogenerated by FlynnLint
// Contents of file after this marker will be overwritten as needed

extension Endeavour {

    @discardableResult
    public func beNewDocument(userUUID: UserUUID,
                              content: Hitch?,
                              _ sender: Actor,
                              _ callback: @escaping ((DocumentInfo?, Document?, Error?) -> Void)) -> Self {
        unsafeSend {
            self._beNewDocument(userUUID: userUUID, content: content) { arg0, arg1, arg2 in
                sender.unsafeSend {
                    callback(arg0, arg1, arg2)
                }
            }
        }
        return self
    }
    @discardableResult
    public func beNewDocument(userUUID: UserUUID,
                              named: Hitch?,
                              content: Hitch?,
                              _ sender: Actor,
                              _ callback: @escaping ((DocumentInfo?, Document?, Error?) -> Void)) -> Self {
        unsafeSend {
            self._beNewDocument(userUUID: userUUID, named: named, content: content) { arg0, arg1, arg2 in
                sender.unsafeSend {
                    callback(arg0, arg1, arg2)
                }
            }
        }
        return self
    }
    @discardableResult
    public func beJoinDocument(userUUID: UserUUID,
                               documentUUID: DocumentUUID,
                               _ sender: Actor,
                               _ callback: @escaping ((DocumentInfo?, Document?, Error?) -> Void)) -> Self {
        unsafeSend {
            self._beJoinDocument(userUUID: userUUID, documentUUID: documentUUID) { arg0, arg1, arg2 in
                sender.unsafeSend {
                    callback(arg0, arg1, arg2)
                }
            }
        }
        return self
    }
    @discardableResult
    public func beLeaveDocument(userUUID: UserUUID,
                                service: Service,
                                documentUUID: DocumentUUID,
                                _ sender: Actor,
                                _ callback: @escaping ((Error?) -> Void)) -> Self {
        unsafeSend {
            self._beLeaveDocument(userUUID: userUUID, service: service, documentUUID: documentUUID) { arg0 in
                sender.unsafeSend {
                    callback(arg0)
                }
            }
        }
        return self
    }

}
